cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
    path('isCart/', is_cart, name='is_cart_instance'),
    path('order/', CreateOrder.as_view(), name='order_received'),
    path('orders', OrdersList.as_view(), name='orders_list'),

]

sportbar/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('captcha/', include('captcha.urls')),
    path('', include('app_sportbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }), ]

cart/models.py
from django.db import models
from app_sportbar.models import MenuPosition
from django.contrib.auth.models import User

# Create your models here.
class Order(models.Model):
    client = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    email = models.EmailField(max_length=50)
    address = models.CharField(max_length=250)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_delivered = models.BooleanField(default=False)
    is_paid = models.BooleanField(default=False)

    # total order cost with get_cost() from related Model OrderItem 
    def get_total_cost(self):
        return sum(item.get_cost() for item in self.order_items.all())
    
    def __str__(self):
        return 'Order {}'.format(self.id)
    
    class Meta:
        ordering = ('-created_at',)

class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='order_items', on_delete=models.CASCADE)
    product = models.ForeignKey(MenuPosition, related_name='products_in_order', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField()

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity
        

    
    

    

cart/forms.py
from django import forms
from .models import Order

# PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    # quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    quantity = forms.IntegerField(min_value=1)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

class OrderForm(forms.ModelForm):
    
    class Meta:
        model = Order
        fields = ('email', 'address')

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from app_sportbar.models import MenuPosition
from .cart import Cart
from .forms import CartAddProductForm, OrderForm
from django.http import JsonResponse
from decimal import Decimal
from django.views.generic import View, ListView
from .models import Order, OrderItem


@require_POST
def cart_add(request, product_id):
    cart_instance = Cart(request)
    product = get_object_or_404(MenuPosition, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        form_data = form.cleaned_data
        quantity=form_data['quantity']
        cart_instance.add(product=product,
                 quantity=quantity,
                 update_quantity=form_data['update'])
        
    # editing cart from cart/detail.html  with product quantity   
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        return JsonResponse({
            'newTotalProductPrice':Decimal(cart_instance.cart[str(product_id)]['price'])*quantity,
            'newTotal':cart_instance.get_total_cost(),
            'product_id':product_id,
            'newQuantity':quantity})
       
    
    else:
        return redirect(request.META.get('HTTP_REFERER'))

# remove from cart
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(MenuPosition, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

# display cart with goods
def cart_detail(request):
    cart_instance = Cart(request)
    form = CartAddProductForm()
    return render(request, 'cart/cart.html', {'cart_instance': cart_instance, 'cart_form':form})
    
def is_cart(request):
    cart_instance = Cart(request)
    if len(cart_instance) > 0:
        return JsonResponse({'response':'yes', 'goodsNumber':len(cart_instance)})
    else:
        return JsonResponse({'response':'no'})

class   CreateOrder(View):
    def get(self, request):
        orderForm = OrderForm()
        return render(request, 'cart/order_form.html', {'order_form':orderForm})
    
    def post(self, request):
        order_form = OrderForm(request.POST)
        cart_instance = Cart(request)
        if order_form.is_valid():
            if len(cart_instance) > 0:
                if request.user.is_authenticated:
                    order = order_form.save(commit=False)
                    order.client = request.user
                    order.save()
                else:
                    order = order_form.save()
            for item in cart_instance:
                OrderItem.objects.create(order=order,
                                         product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'])
            cart_instance.clear()
            return JsonResponse({'response':'success'})           
        else:
            return JsonResponse({'response':'validation error'})

class OrdersList(ListView):
    model = Order

    def get_queryset(self):
        return Order.objects.filter(client=self.request.user)
   

cart/templates/cart/cart.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Your shopping cart
{% endblock %}
{% block content_base %}
<h1>Your shopping cart</h1>
<div class="table-responsive">
  <table class="table align-middle mb-0 bg-white">
    <thead class="bg-light">
      <tr>
        <th>#</th>
        <th>Product</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Total price</th>
        <th>Remove</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart_instance %}
      <tr>
        <td>
          {{forloop.counter}}
        </td>
        <td>
          <div class="d-flex align-items-center">
            <img src="{{item.product.image.url}}" alt="" style="width: 45px; height: 45px" class="rounded-circle" />
            <div class="ms-3">
              <p class="fw-bold mb-1">{{item.product.title}}</p>
            </div>
          </div>
        </td>
        <td>
          <p class="fw-normal mb-1">{{item.price}}$</p>
        </td>
        <td>
          <form action="{% url 'cart:cart_add' item.product.pk %}" method="post" class="editQuantityForm">
            <span class="quantityReal" id="{{item.product.id}}_quantity">{{item.quantity}}</span>
            {% csrf_token %}
            <input type="number" name="quantity" min="1" required="" value="{{item.quantity}}" style="display: none;" class="quantityEdit">
            <input type="hidden" name="update" value="True">
            <button type="button" class="btn btn-link btn-rounded btn-sm fw-bold quantityReal" onclick="editQuantity(event)">
              Edit
            </button>
            <button type="submit" class="btn btn-link btn-rounded btn-sm fw-bold quantityEdit"  style="display: none;">
              Confirm
            </button>
            <button type="button" class="back btn btn-link btn-rounded btn-sm fw-bold quantityEdit"  style="display: none;" onclick="confirmClose(event)">
              Back
            </button>
          </form>
        </td>
        <td>
          <p class="fw-normal mb-1" id="{{item.product.id}}_total_price">{{item.total_price}}$</p>
        </td>
        <td>
          <a href="{% url 'cart:cart_remove' item.product.pk %}"><button type="button" class="btn btn-outline-danger btn-rounded" data-mdb-ripple-color="dark" >Remove from cart</button></a>
        </td>
      </tr>

      {% endfor %}
      <tr>
        <td colspan="4">
          <b>TOTAL</b>
        </td>
        <td><b id="cart_total_cost">{{cart_instance.get_total_cost}}$</b></td>
      </tr>
    </tbody>
  </table>
</div>




<p class="text-right">
  <a href="{% url 'home' %}">
    <button type="button" class="btn btn-success btn-rounded">Continue shopping</button></a>
  <a href="{% url 'cart:order_received' %}"><button type="button" class="btn btn-success btn-rounded">Order</button></a>
</p>
{% endblock content_base %}

cart/templates/cart/order_form.html
{% extends 'base.html' %}
{% load custom_tags %}

{% block content_base %}
<h3>Add information to complete the order</h3>

{% if not request.user.is_authenticated %}
<div class="alert alert-danger" role="alert">
    You cannot access your order history if you are not registered. <a href="{% url 'login' %}">Log in</a>/<a href="{% url 'register' %}">Sign up</a>
</div>
    
{% endif %}
    
{% show_form order_form 'Order' 'cart:order_received' %}




{% endblock content_base %}
    

cart/templates/cart/order_list.html
{% extends 'base.html' %}


{% block content_base %}

{% for object in object_list %}
<div class="table-responsive" style="border: 2px white groove; margin:25px; padding: 15px;">
    <div class="class="d-flex justify-content-start">
        <div>
            Order{{object.pk}}
        </div>
        <div>
            {{object.created_at}}
        </div>
        <div>
        
            {% if object.is_delivered %}
            <i class="fas fa-check " style="color: rgb(121, 248, 10);"> Delivered</i>
            {% else %}
            <i class="fas fa-car-side" style="color: red;"> NOT delivered</i>
            {% endif %}
        </div>
        <div>
        
            {% if object.is_paid %}
            <i class="fas fa-check" style="color: rgb(121, 248, 10);"> Paid</i>
            {% else %}
            <i class="fas fa-credit-card" style="color: red;"> NOT paid</i>
            {% endif %}
        </div>
    </div>
    
    <table class="table align-middle mb-0 bg-white">
        <thead class="bg-light">
            <tr>
                <th>#</th>
                <th>Product</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Total price</th>
                <th></th>
            </tr>
        </thead>
        <tbody>

            {% for order_item in object.order_items.all %}


            <tr>
                <td>
                    {{forloop.counter}}
                </td>
                <td>
                    <div class="d-flex align-items-center">
                        <img src="{{order_item.product.image.url}}" alt="" style="width: 45px; height: 45px"
                            class="rounded-circle" />
                        <div class="ms-3">
                            <p class="fw-bold mb-1">{{order_item.product.title}}</p>
                        </div>
                    </div>
                </td>
                <td>
                    <p class="fw-normal mb-1">{{order_item.price}}$</p>
                </td>
                <td>
                    <p class="fw-normal mb-1">{{order_item.quantity}}</p>
                </td>
                <td>
                    <p class="fw-normal mb-1">{{order_item.get_cost}}$</p>
                </td>
                <td>
                   
                </td>
            </tr>


            {% endfor %}
            <tr>
                <td colspan="4">
                    <b>TOTAL</b>
                </td>
                <td><b id="cart_total_cost">{{object.get_total_cost}}$</b></td>
            </tr>
        </tbody>
    </table>
</div>
{% endfor %}

{% endblock content_base %}