app_sportbar/urls.py
from django.urls import path
from .views import *
from django.views.generic.base import TemplateView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('register/',Register.as_view(), name='register'),
    path('login/',LoggingIn.as_view() , name='login'),
    path('logout/',log_out , name='logout'),
    path('category/<str:slug>/',CategoryDetail.as_view() , name='category'),
    path('category_list/',CategoryList.as_view() , name='categories'),
    path('book_table/',BookTable.as_view() , name='book_table'),
    path('subsribe/',Subscription.as_view() , name='subscribe'),
 
]

cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
    path('isCart/', is_cart, name='is_cart_instance'),
    path('order/', CreateOrder.as_view(), name='order_received'),
    path('orders', OrdersList.as_view(), name='orders_list'),

]

sportbar/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('captcha/', include('captcha.urls')),
    path('', include('app_sportbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }), ]

app_sportbar/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

class Category(models.Model):
    title = models.CharField(max_length = 50)
    image = models.ImageField(upload_to='images/%Y/%m/%d', max_length=100, blank=True)
    description = models.CharField( max_length=150, blank=True)
    slug = models.SlugField(max_length = 50)
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('category', kwargs={'slug': self.slug})


class MenuPosition(models.Model):
    title = models.CharField(max_length=50)
    description = models.CharField( max_length=150, blank=True)
    price = models.DecimalField( max_digits=5, decimal_places=2)
    category =models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/%Y/%m/%d', max_length=100, blank=True)    
    
    def __str__(self):
        return self.title
    
class BookedTable(models.Model):
    client = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    datatime_booked = models.DateTimeField(verbose_name='Choose a date.')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    phone = models.TextField()

class SubscriptionContact(models.Model):
    email = models.EmailField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email
    
    
    
    
    
                                                               

app_sportbar/forms.py
from .models import BookedTable, SubscriptionContact
from django import forms
from captcha.fields import CaptchaField

class BookTableForm(forms.ModelForm):
    
    class Meta:
        model = BookedTable
        fields = ['datatime_booked', 'phone']
        widgets = {
            'datatime_booked':forms.DateTimeInput(attrs={'type':'datetime-local'}),
            'phone':forms.NumberInput(attrs={'type':'tel'})
            }
        

class SubscriptionForm(forms.ModelForm):
    captcha = CaptchaField()
    
    class Meta:
        model = SubscriptionContact
        fields= ['email']
        widgets = {
            'email':forms.EmailInput(attrs={'id':'form5Example21', 'class':'form-control'}),'captcha':forms.TextInput(attrs={'class':'form-control'})
        }

app_sportbar/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import View
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from .models import Category
from django.views.generic import DetailView, ListView, CreateView
from cart.forms import CartAddProductForm
from .forms import BookTableForm, SubscriptionForm
from django.http import JsonResponse





class HomeView(View):
    def get(self, request):
        return render(request, 'app_sportbar/home.html')

        


class Register(View):
   
    def get(self, request):
        form = UserCreationForm()
        return render(request, 'app_sportbar/register.html', {'form':form})
    
    def post(self, request):
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('/')

        return render(request, 'app_sportbar/register.html', {'form':form})

class LoggingIn(View):
    def get(self, request):
        logging_form = AuthenticationForm()
        return render(request, 'app_sportbar/login.html', {'logging_form':logging_form})
    
    def post(self, request):
        logging_form = AuthenticationForm(data=request.POST)
        if logging_form.is_valid():
            user = logging_form.get_user()
            login(request, user)
            return redirect ('/')
        else:
            return render(request, 'app_sportbar/login.html', {'logging_form':logging_form})

def log_out(request):
    logout(request)
    return redirect('home')



class CategoryDetail(DetailView):
    model = Category

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cart_form'] = CartAddProductForm()
        return context

class CategoryList(ListView):
    model = Category

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cart_form'] = CartAddProductForm()
        return context

class BookTable(View):
    def get(self, request):
        form = BookTableForm()
        return render(request, 'app_sportbar/book_table.html', {'form':form})
    
    def post(self,request):
        form = BookTableForm(request.POST)
        if form.is_valid():
            if request.user.is_authenticated:
                booked_table = form.save(commit=False)
                booked_table.client = request.user
                booked_table.save()
            else:
                form.save()
            return JsonResponse({'response':'success'})
        else:
            form = BookTableForm()
            return render(request, 'app_sportbar/book_table.html', {'form':form})
        
class Subscription(CreateView):
    form_class = SubscriptionForm
    
    def form_valid(self, form):
        form.save()
        return JsonResponse({'response':'success'})
    
    def form_invalid(self, form):
        return JsonResponse({'response':'ValidationError'})   

    

app_sportbar/templates/app_sportbar/book_table.html
{% extends 'base.html' %}
{% load custom_tags %}

{% block title %}
  Book a table
{% endblock title %}
  

{% block content_base %}
<h2>Book a table</h2>
<form action="{% url 'book_table' %}" method="post" id="bookTableForm">
  

  {% csrf_token %}
  <div style="text-align: center;">

    {% for field in form %}
    <div class="registrationFormField">
      <div>{{field.label_tag}}</div>
      <div>{{field}}</div>
      <div>{{field.help_text}}</div>
      
      {% for error in field.errors %}
        {{error}}
      {% endfor %}
        
    </div>
    {% endfor %}


    <button type="submit" class="btn btn-warning">Book a table</button>

    <div>
      {% for error in form.non_field_errors %}
        {{error}}
      {% endfor %}

    </div>
      
  </div>
</form>





{% endblock content_base %}

    

app_sportbar/templates/app_sportbar/category_detail.html
{% extends 'base.html' %}
{% load custom_tags %}

{% block title %}
  {{object}}
{% endblock title %}

{% block content_base %}
    {% category object cart_form %}
{% endblock content_base %}

app_sportbar/templates/app_sportbar/category_list.html
{% extends 'base.html' %}
{% load custom_tags %}

{% block title %}
  Menu
{% endblock title %}

{% block content_base %}
  
  {% for category in object_list %}
    {% category category cart_form %}
  {% endfor %}
    
{% endblock content_base %}

app_sportbar/templates/app_sportbar/form_template.html
{% load custom_tags %}

<form action='{{form_action|get_url}}' method="post" id="{{button_text}}Form">
  

  {% csrf_token %}
  <div style="text-align: center;">

    {% for field in form %}
    <div class="registrationFormField">
      <div>{{field.label_tag}}</div>
      <div>{{field}}</div>
      <div>{{field.help_text}}</div>
      {% for error in field.errors %}
      <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
        <symbol id="exclamation-triangle-fill" viewBox="0 0 16 16">
          <path
            d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
        </symbol>
      </svg>
      <div class="alert alert-warning d-flex align-items-center" role="alert">
        <svg class="bi flex-shrink-0 me-2" role="img" aria-label="Warning:">
          <use xlink:href="#exclamation-triangle-fill" />
        </svg>
        <div>
          {{ error }}
        </div>
      </div>
      {% endfor %}
    </div>
    {% endfor %}


    <button type="submit" class="btn btn-warning">{{button_text}}</button>
   
  <div id="{{button_text}}FormError"></div>

    <div>
      {% for error in form.non_field_errors %}
        {{error}}
      {% endfor %}

    </div>
      
  </div>
</form>

app_sportbar/templates/app_sportbar/home.html
{% extends 'base.html' %}
{% load static %}

{% block content_base %}
<div class="slideshow-container">

  <div class="mySlides">
    <img src={% static "app_sportbar/img/close-up-friends.avif" %} style="width:100%">
    <div class="divText">
      <div class="text scale-up-center"><b>Grab Your Beer</b></div>
      <div class="text scale-up-center"><b>WATCH YOUR FAVOURITE GAME</b></div>
      <div class="text scale-up-center"><b>Welcome to the highly-anticipated sports bar ranked first among many of the
          most popular nighttime destinations. Enjoy the latest sporting events and drink cold beer at our bar!</b>
      </div>
      <a href="{% url 'book_table' %}">
        <div class="text scale-up-center"><button type="button" class="btn btn-warning">BOOK A TABLE</button></div>
      </a>
    </div>
  </div>

</div>
</div>

<div class="mySlides ">
  <img src={% static "app_sportbar/img/fun-friends.jpg" %} style="width:100%">
  <div class="divText">
    <div class="text scale-up-center"><b>Enjoy The Game</b></div>
    <div class="text scale-up-center"><b>THE BIG SCREEN EXPERIENCE</b></div>
    <div class="text scale-up-center"><b>We have one of the biggest LED TV panels in the city and that’s why watching
        your favorite game at The Sport Bar guarantees you will enjoy your time.</b></div>
    <a href="{% url 'book_table' %}">
      <div class="text scale-up-center"><button type="button" class="btn btn-warning">BOOK A TABLE</button></div>
    </a>
  </div>
</div>
<div class="mySlides">
  <img src={% static "app_sportbar/img/happy-men.avif" %} style="width:100%">
  <div class="divText">
    <div class="text scale-up-center"><b>Great Place For Everyone</b></div>
    <div class="text scale-up-center"><b>Enjoy Your Company</b></div>
    <div class="text scale-up-center"><b>A good company is what you need to unforgettably spend your time at our bar.
        With a wide variety of snacks and drinks, you and your friends can have the best sports bar experience.</b>
    </div>
    <a href="{% url 'book_table' %}">
      <div class="text scale-up-center"><button type="button" class="btn btn-warning">BOOK A TABLE</button></div>
    </a>
  </div>
</div>

</div>
<br>

<div style="text-align:center">
  <span class="dot"></span>
  <span class="dot"></span>
  <span class="dot"></span>
</div>


<hr>




<script>
  document.getElementById('main').setAttribute('style', 'padding-top:0;')
</script>

{% endblock content_base %}

app_sportbar/templates/app_sportbar/login.html
{% extends 'base.html' %}
{% load custom_tags %}

{% block title %}
  Log In
{% endblock title %}

{% block content_base %}

<h2>Login form</h2>
    {% show_form logging_form 'Log in' %}
{% endblock content_base %}

app_sportbar/templates/app_sportbar/menu.html
<div class="note note-warning mb-3">
  <strong>{{category.title}}:</strong>{{category.description}}
</div>


<div class="row">
  {% for item in category.menuposition_set.all %}
  <div class="col-md-4">
    <div class="card">
      <img src="{{item.image.url}}"/>
      <div class="card-body">
        <h5 class="card-title" id="card-title{{item.id}}">{{item.title}}</h5>
        <p class="card-text">{{item.description}}</p>
        <p class="card-text">{{item.price}}</p>
        <form action="{% url 'cart:cart_add' item.id %}" method="post" id="addToCartForm{{item.id}}">
            {% csrf_token %}
            {{cart_form}}
            <input type="button" value="Add to cart" class="btn btn-primary" data-mdb-toggle="modal" data-mdb-target="#exampleModal" data-get-product-title="card-title{{item.id}}" onclick="passInModal(event)">
        </form>
        
      </div>
    </div>
  </div>
  {% endfor %}
</div>  


<!-- Modal window -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title modal-font
        " id="exampleModalLabel"></h5>
        <button type="button" class="btn-close" data-mdb-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body modal-font" id="cartMessage">You are going to add <span id="modalProductTitle"></span> to your shopping cart</div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-mdb-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" id="addToCartButton2">Add to cart</button>
        <a href="{% url 'cart:cart_detail' %}"><button type="button" class="btn btn-info">Just go to cart</button></a>
      </div>
    </div>
  </div>
</div>

app_sportbar/templates/app_sportbar/register.html
{% extends 'base.html' %}
{% load custom_tags %}


{% block title %}
Sign up
{% endblock title %}
    

{% block content_base %}
<h2>Sign up form</h2>
    {% show_form form 'Registrate' %}
{% endblock content_base %}