cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
    path('isCart/', is_cart, name='is_cart_instance'),
    path('order/', CreateOrder.as_view(), name='order_received'),
    path('orders', OrdersList.as_view(), name='orders_list'),

]

sportbar/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('captcha/', include('captcha.urls')),
    path('', include('app_sportbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }), ]

templates/base.html
{% load static %}
{% load custom_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>
    
    {% block title %}
    Sportbar
    {% endblock title %}
      
    </title>

  <!-- bootstrap -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">


  <!-- Font Awesome -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet" />
  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />

  <!-- MDB -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.2.0/mdb.min.css" rel="stylesheet" />



  <!-- Template Main CSS File -->
  <link href={% static 'app_sportbar/css/style.css' %} rel="stylesheet">
  <link href={% static 'app_sportbar/css/allauth.css' %} rel="stylesheet">
  <link href={% static 'app_sportbar/css/menu_page.css' %} rel="stylesheet">
  <link href={% static 'cart/css/cart.css' %} rel="stylesheet">

</head>

<body>

 {% show_navbar request.user%}

  <main id="main">
    <div id="content">
      {% block content_base %}{% endblock content_base %}
    </div>
  </main>
  <!-- End #main -->

  {% include '_inc/_footer.html' %}

  <!-- making django url accessable in js -->
  <input type="hidden" value='{% url 'cart:is_cart_instance' %}' id="is_cart_url">
  <!-- End Footer -->
  <script src={% static "app_sportbar/js/main.js" %}></script>
  <script src={% static "cart/js/cart.js" %}></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
    crossorigin="anonymous"></script>
  <!-- MDB -->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.2.0/mdb.min.js"></script>
  
</body>

</html>

templates/navbar.html
<!-- ======================Navbar=========================== -->
<div class="nav">
  <input type="checkbox" id="nav-check">
  <div class="nav-header">
    <div class="nav-title">

      <!-- added href to home page with another url, only for order_form.html for not to show confirmation modal window from here  -->
      <a href="{% url 'home' %}">Home</a>

    </div>
  </div>
  <!-- _________small width menu icon -->
  <div class="nav-btn">
    <label for="nav-check">
      <span></span>
      <span></span>
      <span></span>
    </label>
  </div>

  <div class="nav-links">

    <a class="btn-primary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-mdb-toggle="dropdown"
      aria-expanded="false">
      Menu
    </a>
    <!-- __________display categories -->
    <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
      {% for category in categories %}
      <li><a class="dropdown-item" href="{{category.get_absolute_url}}">{{category.title}} <img
            src="{{category.image.url}}" alt=""></a></li>
      {% endfor %}
    </ul>
    <!-- ___________ -->
    <a href="">Link</a>


  </div>
  <div id='nav-div-right'>
    <form action="{% url 'categories' %}">
      <button type="submit" class="btn btn-warning">ORDER ONLINE</button>
    </form>

    {% if request_user.is_authenticated %}
    <!-- Avatar -->
    <div class="dropdown">
      <a class="dropdown-toggle d-flex align-items-center hidden-arrow" href="#" id="navbarDropdownMenuAvatar"
        role="button" data-mdb-toggle="dropdown" aria-expanded="false">
        <img src="https://mdbcdn.b-cdn.net/img/new/avatars/2.webp" class="rounded-circle" height="25"
          alt="Black and White Portrait of a Man" loading="lazy">
      {{request_user.username}}</a>
      <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuAvatar">
        <li>
          <a class="dropdown-item disabled" href="#">My profile</a>
        </li>
        <li>
          <a class="dropdown-item" href="{% url 'cart:orders_list' %}">My orders</a>
        </li>
        <li>
          <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
        </li>
      </ul>
    </div>
    {% else %}
    <div class="d-flex align-items-center">
      <form action="{% url 'login' %}">
        <button type="submit" class="btn btn-primary">Log in</button>
      </form>
      <form action="{% url 'register' %}">
        <button type="submit" class="btn btn-primary">Sign up</button>
      </form>
      {% endif %}
      <i class="fas fa-shopping-cart fa-2x" id="emptyCart"></i>
      <a href="{% url 'cart:cart_detail' %}" id="notEmptyCart">
        <i class="fas fa-cart-arrow-down fa-2x" style="color: rgb(255, 35, 35);"></i>
        <i class="fas" style="color: rgb(255, 35, 35);" id="goodsNumber"></i>
      </a>

  </div>
</div>
<!-- Container wrapper -->
</nav>
<!-- Navbar -->
</div>
</div>
<!-- ======================End Navbar=========================== -->